version: "2"

services:
  ethereum:
    image: ethnode/parity:1.4.4
    volumes:
      - /data/store/parity:/root/.parity
    command: ' --port 30304'
  netstats:
    image: ethnode/stats
    environment:
      instance: 
      contact_details: 
    depends_on:
      - ethereum
