version: "2"

services:
  ethereum:
    image: ethnode/geth
    volumes:
      - /data/store/geth:/root/.ethereum
    command: " --cache 1024"
  netstats:
    image: ethnode/stats
    environment:
      instance: 
      contact_details: 
    depends_on:
      - ethereum
