version: "2"

services:
  ethereum:
    image: ethnode/geth:1.4.17
    volumes:
      - /data/store/geth:/root/.ethereum
  netstats:
    image: ethnode/stats
    environment:
      instance: 
      contact_details: 
    depends_on:
      - ethereum
